services:
  app:
    build: .
    ports:
      - 127.0.0.1:3000:3000
    environment:
      ENVIRONMENT: prod
    command: npm run start
  mysql:
    image: mysql:8.3
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - .env
      - .db.env
volumes:
  mysql-data:
