services:
  app:
    build: .
    ports:
      - 127.0.0.1:3000:3000
    command: npm run start
    environment:
      MYSQL_HOST: mysql:3306
    env_file:
      - .env
  mysql:
    image: mysql:8.3
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: very_secret_pwd
volumes:
  mysql-data:
